variables:
  NODE_VERSION: "20.19.0"

create-pages:
  pages:
    publish: dist
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - curl -fsSL https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | tar -xJ
    - export PATH="$PWD/node-v${NODE_VERSION}-linux-x64/bin:$PATH"
    - node --version
    - npm install
  script:
    - npm run build
