services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${HOST_PORT:-47293}:47293"
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
