import type { Material } from '@types'

export const seedMaterials: Material[] = [
  {
    id: 'seed-lifepo4',
    name: 'LiFePO4',
    category: 'Active Material',
    grainSize: 1.0,
    density: 3.6,
    molecularWeight: 157.76,
    eConductivity: 1e-9,
    liConductivity: 1e-5,
    reductionPotential: 3.4,
    valency: 1,
  },
  {
    id: 'seed-licoo2',
    name: 'LiCoO2',
    category: 'Active Material',
    grainSize: 5.0,
    density: 5.05,
    molecularWeight: 97.87,
    eConductivity: 1e-4,
    liConductivity: 1e-7,
    reductionPotential: 3.9,
    valency: 1,
  },
  {
    id: 'seed-nmc622',
    name: 'NMC-622',
    category: 'Active Material',
    grainSize: 10.0,
    density: 4.7,
    molecularWeight: 96.46,
    eConductivity: 1e-5,
    liConductivity: 1e-8,
    reductionPotential: 3.7,
    valency: 1,
  },
  {
    id: 'seed-lgps',
    name: 'LGPS',
    category: 'Solid Electrolyte',
    grainSize: 2.0,
    density: 1.95,
    molecularWeight: 436.02,
    eConductivity: 1e-9,
    liConductivity: 1.2e-2,
  },
  {
    id: 'seed-llzo',
    name: 'LLZO',
    category: 'Solid Electrolyte',
    grainSize: 5.0,
    density: 5.1,
    molecularWeight: 768.07,
    eConductivity: 1e-10,
    liConductivity: 3e-4,
  },
  {
    id: 'seed-li6ps5cl',
    name: 'Li6PS5Cl',
    category: 'Solid Electrolyte',
    grainSize: 1.5,
    density: 1.64,
    molecularWeight: 283.33,
    eConductivity: 1e-10,
    liConductivity: 1.3e-3,
  },
  {
    id: 'seed-carbon-black',
    name: 'Carbon Black',
    category: 'Conductor',
    grainSize: 0.05,
    density: 1.8,
    molecularWeight: 12.01,
    eConductivity: 10,
    liConductivity: 0,
  },
  {
    id: 'seed-vgcf',
    name: 'VGCF',
    category: 'Conductor',
    grainSize: 0.15,
    density: 2.0,
    molecularWeight: 12.01,
    eConductivity: 100,
    liConductivity: 0,
  },
]
